---
extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false", "on", "off"]
