[build]
  base = "web"
  command = "pnpm build"
  publish = "out"

[build.environment]
  PNPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle client-side routing for 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 